### ISSUE TITLE
md support

### ISSUE THREAD

**Issue by KosukeMizuno** [KosukeMizuno/esapy#21]
mdファイルをアップするときに、記事作成に成功したのにエラーが出る

```
[2020-06-13 15:41:07,664] esapy.processor INFO: Intermediate markdown file has been saved.
[2020-06-13 15:41:07,665] esapy.entrypoint INFO: publish mode=force, result of preprocess=True, ... pu
blish: True
[2020-06-13 15:41:07,665] esapy.processor INFO: Uploading markdown body ...
[2020-06-13 15:41:07,669] esapy.processor INFO: Gathering information for create post
[2020-06-13 15:41:07,670] esapy.processor INFO: This file has not been uploaded before. ==> create new
 post
[2020-06-13 15:41:07,670] esapy.api INFO: Creating new post
[2020-06-13 15:41:08,308] esapy.api INFO: New post was successfully created.
[2020-06-13 15:41:08,309] esapy.api INFO: URL of the created post: https://dia-pe-titech.esa.io/posts/
590
[2020-06-13 15:41:08,311] esapy.processor INFO: Removing temporal working directory
Traceback (most recent call last):
  File "/home/mizuno/.pyenv/versions/3.7.7/bin/esa", line 8, in <module>
    sys.exit(main())
  File "/home/mizuno/.pyenv/versions/3.7.7/lib/python3.7/site-packages/esapy/entrypoint.py", line 183,
 in main
    args.handler(args)
  File "/home/mizuno/.pyenv/versions/3.7.7/lib/python3.7/site-packages/esapy/entrypoint.py", line 57,
in command_up
    post_url = proc.upload_body()
  File "/home/mizuno/.pyenv/versions/3.7.7/lib/python3.7/site-packages/esapy/processor.py", line 296,
in upload_body
    self.nbjson
AttributeError: 'MarkdownProcessor' object has no attribute 'nbjson'
```

**Comment by KosukeMizuno** [comment]
This bug was solved at >=1.3.2.
