### ISSUE TITLE
実行時にサブコマンドがない場合に発生するエラーのbugfix

### ISSUE THREAD

**Issue by kiotex** [KosukeMizuno/esapy#28]
`esa -v`や単に`esa`などと実行時にサブコマンドを指定しない場合、次のようなエラーが発生した。
```bash
Traceback (most recent call last):
  File "c:\users\__username__\.conda\envs\qudi\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\__username__\.conda\envs\qudi\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\__username__\.conda\envs\qudi\Scripts\esa.exe\__main__.py", line 7, in <module>
  File "c:\users\__username__\.conda\envs\qudi\lib\site-packages\esapy\entrypoint.py", line 189, in main
    args.handler(args)
AttributeError: 'Namespace' object has no attribute 'handler'
```

**Comment by kiotex** [comment]
esapy/src/esapy/entrypoint.pyの189行目の`args.handler(args)`でhandlerを持つか場合分けをしてないために起こるみたい。

```python
# Pythonのargparseでサブコマンドを実現する
# https://qiita.com/oohira/items/308bbd33a77200a35a3d
# より

# コマンドライン引数をパースして対応するハンドラ関数を実行
args = parser.parse_args()
if hasattr(args, 'handler'):
    args.handler(args)
else:
    # 未知のサブコマンドの場合はヘルプを表示
    parser.print_help()
```

**Comment by KosukeMizuno** [comment]
fixed.
